title: "Home of the makerspace @ Telenor Fornebu"
description: "The awesome website for the makerspace @ Telenor Fornebu in Norway"
baseurl: ""
url: "https://fornebumakerspace.github.io"
github_username: FornebuMakerspace

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
